language: node_js
node_js:
- '4.3'
after_success:
  - npm run coveralls
before_deploy:
  - npm prune --production
deploy:
  provider: lambda
  function_name: metrics-addon
  description: Computes additional metrics for AWS resources
  module_name: aws-metrics-addon
  handler_name: handleMetric
  role: arn:aws:iam::608300940987:role/lambda-metrics-addon
  runtime: nodejs4.3
  memory_size: 128
  timeout: 20
  region: eu-west-1
  access_key_id:
    secure: pxRvpnT6vfab8Nrj7qVJHRBhLi2FPRqyrJRaZfhWl+HrIkvcRiNMEmXcGuKmutZIDJGsMlOWEmuP0mAi+vb98+BiGIsEOVVgfKKdLBwFa3KwltHn/OZTblDVWhBsRjM1tuY1i/ZMuTmhm7wYt/JIvr9R4aP1WD4qzx3IB5wORLnaLVr7uYkIui+eI57aOEXeObmDwLx6Dl6XV0mLbobscSjk/AIXSYlofODl+FaivHlRJT7mfoLDCvD126/V3feLY2J2cwmag3faFA/Fq/yWMES8RAMxADNTvFvGcd7e32DlhnCwhCWnQx6dLVLUOUhCMVj9GEcadJ7TWEZBuLIF4hLl9TtUX+tw4IG8w4Wv41hDvqEj2EwfQeday0BdaKyoKLJdFhBDHESRkH2v+zJl4OjUlKeugfPOwooSAmLRzMYECGj79/NBtl0hXBE5/LDlb6BqW96ObKw4bwcNsKdx0KIGeZR7i6C8T2iGbud9Jo9RfmRTrScVCrkhkHdQZNa5BirD/iD3wGvSbAj3LgzCeNIcBx9w/9JWb9NNlWuDm9RYt83omNNWlZT/b3HeedGHGq1gG7RieOhabEE9LIllFD9wLDJCbfxZ4QlA1INJrfzl53z9RemZWY7wRt+7oIjMCZbCyjzFEyNY+FyT/4NuiV5DOzL6bzz3kTLpGs/cHCg=
  secret_access_key:
    secure: BJmi4mBm5fEQ0YAC0hL9lNdxaWW+nSPRRCpORZbod/qki2lKqHvKTG38OxWtxDLTHMRedEVN4U6Ptl0ly6pqEs42cAOQkPpZg2UOjw5Ik5PLoseT7UjXmA5iFiRoWjsaj2j5q62x//7wAABbClkq3n/3I+cxgMUzgGzKyc28jj8JP5rRhz2NbsHYpJuIYEvEKEA2laYaLLsf+c10H2ISgy7mcPA2NQysbbw6k2XKMnQ9U7TeNtYZaYYk3TDYvFLTiUwlccUGfcGVgVWIoCty2PVzLzdGX4T8YhEwex2e1OZPIl3u29E+LsE55x9iDckyMAlBN95yC6VGMXkd240W2kyJr8tJ7eAGDYC0+sI91uDprJCw6uAeppkZL3lzNRoAFU8Aqvgf8kUm6nC4dCdQlbVYR1NwIueJ89WV1VhBnbBE+k2qmCGYrTEQxkn6/JKUiOWH9KYC0UGlJqlAOCRVQav1hb0MFD49+W3QnCqsHU4UbogbjdmA9fRvEPVN+tQTlxhiP8ufZikKaQ8wGZiUkWrdrCmnONZIlxpYlKLBAOu3tO7jjtLbwxkun/adqiASJGw1Yf62tF1bUQLHCw8HbpRdNjrkbq+T20xUMfCsplGJ4YAwSWhFJe2ziIb5mYn4LgJKMBmkYNhIJqDkLoOLTK2YA+4jQrJeutbQt947T2U=
  on:
    branch: master
