language: node_js
node_js:
- '12.16'
after_success:
  - npm run coveralls
before_deploy:
  - yarn install --production
deploy:
  provider: lambda
  function_name: metrics-addon
  description: Computes additional metrics for AWS resources
  module_name: index
  handler_name: handle
  role: arn:aws:iam::608300940987:role/lambda-metrics-addon
  runtime: nodejs12.x
  memory_size: 128
  timeout: 20
  region: eu-west-1
  access_key_id:
    secure: PIp3AEC6MSPDE7sBJZymedxErRfJ1PeQQq6n0K0wdBRUViWYwJs5B7QBLKyURWpIgYoHSSi08TSpxwWedt4JZwjCvthB9fuFT4oddSRsQuKuhdbPm7m7Ol7ybmP0E7L+pAUGcS2yi5PbQ5RKkoOXjnSR7eqPuyvZirJAGxT4GcIQx0WWxjVaiiMbLV1JDFlVIkmxukE/gZDjNqpArf3NfnRc8HGJe0mVOktWOlQRSqeOnrYo0bpB7AosDRUFk8DDlQqXTwtYR3LbYsm6+Wp8IqXB4iyBdbZGEPyT4eVU10xbPDyXKnMyhI2Qyxu3puFXFquGEhk7uJIEjPOMcxU7JNI+FpnL1W2mOYe2/WmWfs3kDs6o0OwqhwNUn0qMTFqdSCOYCyf1zpKV3+wT4Se6fWVKgL29mgD+sHQTuqGU/sbQAs2z5+R1LEt+3ZakuxCc4uSxEPmmQyS5qlXpb4T5zXE/U5FmWN1hDX7uT4wzFPKX2mSYWuU0nQLo1mR0/CPU7pi205shg868qXBPeSbTVh0hr2MwgIF1fOK8awtkT6q1ponOwp+2EcfUyEtZNrfQHL7EPEx6Zkic+W9eNoshxY+P7/NTdUQ2FL878FORvLwL3YnT2zH8NgPIjuzYOSxgLriqUwBRfbjQKcgYOF5/s630P/8L8qurzMNjYHpWeIA=
  secret_access_key:
    secure: h4nJRMEm0P1mCCXkKWH+O4fBP5lqiTQSoST6euYe+JadCYj0BbRjOT+7UPBKUOlz8pPOw5trwuiZdVneyyTqfaq1z0BO7tc2MXhikf5CFPsPqChlC+xRISyyCI2a6PHzBDycVreXX7e9k95pn/ddLrGoT6jcQwGi06bhfo1zr43IR/8OBRKX1nUsjsfH0eih7AwKQvZFvzUIoS2pjFVPfFusr7chYuvKeDcYtM2t4hh20SXnwXt4unvCb6pHvOvj9zVdLzrIQg2TcHFA9PhXUbPc023gvgzpGlaElC11bhQsEDXsQA5EEGnT8E+dnVaumJsCjEZUjY6EFitjY02AYFfucmW0IL85tmccBY3iGPmmEP2PR0coMW9bmdeySSehb+7zYncueyeqESUmhN/vDvpK1bgNlLBz58vadaYCEasmJWh/U1AwcZZfI9vCI/TpSRIOSZEMfmDZoU8bxkMxjbp6556yL3x+bAu6yWrTTSsQbHvS1uRFQRNFC3aIoho1ilzJfjmGKWHWscVl0nSpJvikREKqHeXtDEHGRQaAZtIEKX0RsJDUnkwDALY/hiZiPrOXprAU4S44HcFDIQfXQeYnV3XQ8sD+xfXizTxkKmBpVlYzPDpXqYR/wECaYFZE3HbVV+iT/yiosxOi7rIMA6qigTw1QHOLN/YCc8TIJ5A=
  on:
    branch: master
